version: '3.7'
services:
  backend:
    build:
      context: ${PWD}
      dockerfile: ./Dockerfile.dev
    command: npm run dev # <-- Auto reload enabled
    volumes:
      - ${PWD}:/usr/app/
      - ${PWD}/package.json:/usr/app/package.json
      - ${PWD}/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - backend
    depends_on:
      - jaeger
    environment:
      PORT: 3000
      NODE_ENV: development
      TRACING_GRPC_ENDPOINT: grpc://jaeger:6832

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - backend

networks:
  backend:
